spring: 
  api: 
    saga-node: 
      context-path: /v1/bian-3/core/payment/10.0.0/initpayment
      hosturl: /initiate
      jolt-filename: saga-node404328-jolt.json
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${mysql_pwd}
    url: jdbc:mysql://${mysql_url}:3306/camunda
    username: ${mysql_user}
